---
name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pycryptodomex
          pip install pywin32

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/**/*.exe
